- name: Create Release
  # You may pin to the exact commit or the version.
  # uses: ncipollo/release-action@4b71ee3b25951e6098e7434cdc485edc5b3adab2
  uses: ncipollo/release-action@v1.7.3
  with:
    # An optional flag which indicates if we should update a release if it already exists. Defaults to false.
    allowUpdates: # optional, default is 
    # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
    artifact: # optional, default is 
    # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
    artifacts: # optional, default is 
    # The content type of the artifact. Defaults to raw
    artifactContentType: # optional, default is 
    # An optional body for the release.
    body: # optional, default is 
    # An optional body file for the release. This should be the path to the file
    bodyFile: # optional, default is 
    # An optional commit reference. This will be used to create the tag if it does not exist.
    commit: # optional, default is 
    # Optionally marks this release as a draft release. Set to true to enable.
    draft: # optional, default is 
    # An optional name for the release. If this is omitted the tag will be used.
    name: # optional, default is 
    # Indicates if the release body should be omitted.
    omitBody: # optional, default is false
    # Indicates if the release body should be omitted during updates. The body will still be applied for newly created releases. This will preserve the existing body during updates.
    omitBodyDuringUpdate: # optional, default is false
    # Indicates if the release name should be omitted.
    omitName: # optional, default is false
    # Indicates if the release name should be omitted during updates. The name will still be applied for newly created releases. This will preserve the existing name during updates.
    omitNameDuringUpdate: # optional, default is false
    # Optionally marks this release as prerelease. Set to true to enable.
    prerelease: # optional, default is 
    # Indicates if existing release artifacts should be replaced. Defaults to true.
    replacesArtifacts: # optional, default is true
    # An optional tag for the release. If this is omitted the git ref will be used (if it is a tag).
    tag: # optional, default is 
    # The Github token.
    token: # default is 
